### PR TITLE
Pass all events to basesink

### PR DESCRIPTION
**Pull request by mx3L**

### CODE REVIEW

**Comment by mx3L** [comment]
We are sometimes experiencing deadlock when trying to change audio track from paused state after applying this patches. So I'm closing this pull request until it's solved.

**Comment by mx3L** [comment]
We find out that these patches are not the cause of the issue, since the deadlock is there with or without them. 
It should be safe to apply them.

**Comment by mx3L** [comment]
Can somebody look at this?

**Comment by eriksl** [comment]
I hope to have time for it soon.

**Comment by eriksl** [comment]
I have applied it to gst-1, I guess we will find out soon enough if it breaks things.

**Pull request closed without merging**
