### PR TITLE
Improve divx, xvid playback

### PR DESCRIPTION
**Pull request by mx3L**
http://forums.openpli.org/topic/39326-gstreamer10-and-mpeg4-part2/?view=findpost&p=512179

### CODE REVIEW

**Comment by eriksl** [comment]
Please test thorougly (not only on mpeg4p2 material).

BTW I'd prefer to refer to it as "improve divx playback" as the b-frames packing has nothing to do with the codec, it's a container (avi...) issue. If divx had been smart enough to use quicktime, this would never have been an issue ;-)

**Comment by mx3L** [comment]
Hello,

> BTW I'd prefer to refer to it as "improve divx playback"

I agree, title changed.

> Please test thorougly (not only on mpeg4p2 material).

AFAIK it's now used as default for quite some time in other images like OpenATV, where they use multibox-dvbmediasink with this patch already applied - https://github.com/christophecvr/gstreamer1.0-plugin-multibox-dvbmediasink/commit/5b0828b07f5dfb79cefa5755ead208bb881f8b23

Also I've tested it on all my test samples(divx4,5,xvid{packed unpacked}) on vusolosev2 and et4x00, @athoik tested it on dm800se, all with success.

We are also using it with success in exteplayer3 which is ffmpeg based solution - https://github.com/samsamsam-iptvplayer/exteplayer3/commit/0c7db0eb9b9b799dc5e74614b150d2c060f63015.

So, I would say it's quite tested solution.

**Comment by mx3L** [comment]
There is no need to test non-mpeg4p2 material, since mpeg4p2unpack plugin is only selected when mpeg4-part2 material is used, to be precise when it has these caps on it's sinkpad:

```
+    GST_STATIC_CAPS ("video/mpeg, "
+        "mpegversion = (int) 4, " "systemstream = (boolean) false; "
+        "video/x-divx, " "divxversion = (int) [ 4, 5 ]")
+    );
```

**Comment by athoik** [comment]
Using a separate divx unpacker sink is great idea! 

Also keeps the video sink simpler and easier to maintain!

@mx3L :+1:

**Comment by eriksl** [comment]
I will commit this friday, remind me might I forget.

**Comment by eriksl** [comment]
Applied.

**Pull request closed without merging**
